Repository mmt-12/back-end, pull requests merged in 2025-09, with the labels that each got.

#116 Fix/104 jwt 검증에 leeway 설정 추가
  memento/src/main/java/com/memento/server/api/service/auth/jwt/JwtTokenProvider.java
Labels: bug

#127 Feature/117 알림 목록 조회후, 조회된 알림들을 읽음 처리로 변경
  memento/src/main/java/com/memento/server/api/service/notification/NotificationService.java
  memento/src/main/java/com/memento/server/api/service/notification/dto/response/NotificationResponse.java
  memento/src/main/java/com/memento/server/domain/notification/Notification.java
  memento/src/main/java/com/memento/server/domain/notification/NotificationRepositoryCustom.java
  memento/src/main/java/com/memento/server/domain/notification/NotificationRepositoryImpl.java
  memento/src/test/java/com/memento/server/spring/domain/notification/NotificationRepositoryTest.java
Labels: feature

#126 Fix/109 JWT의 MemberClaim을 검증하는 Validator 추가
  memento/src/main/java/com/memento/server/api/service/auth/jwt/JwtTokenProvider.java
  memento/src/main/java/com/memento/server/config/filter/JwtFilter.java
  memento/src/main/java/com/memento/server/config/filter/MemberClaimValidator.java
  memento/src/test/java/com/memento/server/spring/api/controller/ControllerTestSupport.java
Labels: bug, refactor

#149 Fix/git ignore .vscode
  .gitignore
Labels: config

#151 fix : sse 연결 유지 용 스케줄 구현
  memento/src/main/java/com/memento/server/MementoApplication.java
  memento/src/main/java/com/memento/server/client/sse/SseController.java
  memento/src/main/java/com/memento/server/client/sse/SseEmitterRepository.java
  memento/src/main/java/com/memento/server/client/sse/SseService.java
Labels: bug

#154 fix : post 수정 시 request.oldPictures String(url)로 변경
  memento/src/docs/asciidoc/api/v1/post/post-update.adoc
  memento/src/main/java/com/memento/server/api/controller/post/dto/UpdatePostRequest.java
  memento/src/main/java/com/memento/server/api/service/post/PostService.java
  memento/src/main/java/com/memento/server/domain/post/PostImageRepository.java
  memento/src/test/java/com/memento/server/docs/post/PostControllerDocsTest.java
  memento/src/test/java/com/memento/server/spring/api/controller/post/PostControllerTest.java
  memento/src/test/java/com/memento/server/spring/api/service/achievement/AchievementEventTest.java
Labels: bug
