Repository mmt-12/back-end, pull requests merged in 2025-10, with the labels that each got.

#158 Feature/129 Token Refresh api 추가
  memento/src/docs/asciidoc/api/v1/auth/auth-refresh-token.adoc
  memento/src/docs/asciidoc/api/v1/auth/auth.adoc
  memento/src/main/java/com/memento/server/api/controller/auth/AuthController.java
  memento/src/main/java/com/memento/server/api/controller/auth/dto/TokenRefreshRequest.java
  memento/src/main/java/com/memento/server/api/service/auth/AuthService.java
  memento/src/main/java/com/memento/server/api/service/member/MemberService.java
  memento/src/main/java/com/memento/server/config/SecurityConfig.java
  memento/src/main/java/com/memento/server/config/filter/JwtFilter.java
  memento/src/test/java/com/memento/server/docs/auth/AuthControllerDocsTest.java
  memento/src/test/java/com/memento/server/spring/config/TestSecurityConfig.java
Labels: docs, feature

#161 Fix/159 토큰 발급 로직 수정
  memento/src/main/java/com/memento/server/api/service/auth/AuthService.java
  memento/src/main/java/com/memento/server/api/service/auth/jwt/JwtTokenProvider.java
  memento/src/main/java/com/memento/server/config/filter/JwtFilter.java
Labels: bug

#164 REFACTOR/163 memory readAll 쿼리 수정
  memento/src/main/java/com/memento/server/api/controller/memory/dto/ReadAllMemoryResponse.java
  memento/src/main/java/com/memento/server/api/service/memory/MemoryService.java
  memento/src/main/java/com/memento/server/api/service/memory/dto/MemoryItem.java
  memento/src/main/java/com/memento/server/domain/memory/MemoryRepository.java
  memento/src/test/java/com/memento/server/spring/domain/memory/MemoryRepositoryTest.java
Labels: refactor

#167 feat : 전용 업적 및 출석 업적 API 구현
  db/mysql/dev/z_data1_general.sql
  memento/src/docs/asciidoc/api/v1/achievement/achievement-attendance.adoc
  memento/src/docs/asciidoc/api/v1/achievement/achievement-create.adoc
  memento/src/docs/asciidoc/api/v1/achievement/achievement-exclusive.adoc
  memento/src/docs/asciidoc/api/v1/achievement/achievement.adoc
  memento/src/main/java/com/memento/server/api/controller/achievement/AchievementController.java
  memento/src/main/java/com/memento/server/api/service/achievement/AchievementService.java
  memento/src/main/java/com/memento/server/api/service/auth/AuthService.java
  memento/src/main/java/com/memento/server/api/service/member/MemberService.java
  memento/src/test/java/com/memento/server/docs/achievement/AchievementControllerDocsTest.java
  memento/src/test/java/com/memento/server/spring/api/controller/achievement/AchievementControllerTest.java
  memento/src/test/java/com/memento/server/spring/api/service/achievement/AchievementEventTest.java
  memento/src/test/java/com/memento/server/spring/api/service/achievement/AchievementServiceTest.java
Labels: feature
